### ISSUE TITLE
Spin off client

### ISSUE THREAD

**Issue by till** [SURFnet/yubikey-api-client-bundle#16]
I am not using symfony, but would you mind spinning off the client code?

**Comment by DRvanR** [comment]
Sounds like a good plan - does require some work though with the new repo and all. I propose we do this as part of a new 2.0 release of the Bundle. Unfortunately I cannot give a timeframe, but will get back about this this week (hopefully wednesday).

**Comment by till** [comment]
@DRvanR that's fine. Thanks for considering it! :) I will patiently wait! (Btw, nice work on all of this!)

**Comment by rjkip** [comment]
@till, could you verify the [development branch of the client library](https://github.com/SURFnet/yubikey-api-client) works for you? If so, I will release a 1.0.0 as soon as possible.

**Comment by rjkip** [comment]
Installed separate bundle/client in Step-up platform. All is in working order.

**Comment by till** [comment]
@rjkip sorry, didn't get to that yet. But it _seems_ to work! Will try more on the weekend!
