### ISSUE TITLE
Symfony 3 Ready

### ISSUE THREAD

**Issue by Huskynarr** [SURFnet/yubikey-api-client-bundle#6]
The Bundle isn't compatible with Symfony 3.

**Comment by pmeulen** [comment]
Hi Huskynarr!

Did you test this bundle with Symfony 3? Which version? Does it require any other changes?

I had a discussion with colleges here on how to approach SF3 compatibility in general. Policy here is to target the LTS releases (2.7, 2.8, 3.4). We currently targeting 2.7 LTS which goes EOL in 05/2019, which gives us some time to upgrade. That doesn't say we're not open to receive PRs that target compatibility with later Symfony version, like SF3. It might not be that easy to target the 2.7 and 3.x SF versions from the same codebase:

* composer.lock file will be different
* Upgrade notes are quite extensive, someone will need to go though then and see what needs to be fixed: https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md

What I want to do is make a branch for Symfony 3 compatibility and gather changes there.

Let me know what you think.

**Comment by JHGitty** [comment]
There are a lot of bundles out there which Support Symfony 3.0. You should remove ``composer.lock`` from this bündle. The allowed dependencies will be handled by the entries in ``composer.json``. That is the way the most bundles are working these days.

The work to upgrade to Symfony 3 is not that hard, you just need the time to do it. :+1: The best case is to have a Symfony 2.8 application which use this bündle to see the deprecation notices. The other way is to just ask Travis CI about Symfony 3 but for that you need good unit testing.

**Comment by Huskynarr** [comment]
:+1:

**Comment by JHGitty** [comment]
@Huskynarr Please close this issue. #7 has been merged.
